WANDB_PROJECT=vision-alignment-Qwen1.5-0.5B \
torchrun --nproc_per_node 8 \
-m vision_alignment \
--model_name_or_path mesolitica/malaysian-Qwen1.5-0.5B-16k-instructions \
--image_encoder_name_or_path google/siglip-base-patch16-384 \
--train_file mosaic-vision \
--per_device_train_batch_size 12 \
--gradient_accumulation_steps 1 \
--num_train_epochs 3 \
--save_strategy "steps" \
--save_steps 100 \
--save_total_limit 2 \
--learning_rate 1e-4 \
--weight_decay 0. \
--warmup_ratio 0.03 \
--logging_steps 1 \
--do_train \
--bf16 True \
--gradient_checkpointing True \
--output_dir "vision-alignment-qwen0.5" \
--use_flash_attention2 True \
--block_size 2048